<?php
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
$this->headLink()->appendStylesheet($this->assetUrl('css/group.css', 'Group'));
$this->headScript()->appendFile($this->assetUrl('js/group.js', 'Group'));
$removeStr = $escape($translate('Remove group'));
$groupTemplate = '
<tr>
    <td class="group-name"></td>
    <td>
        <ul class="actions">
            <li>
                <a href="#" class="o-icon-delete" title="' . $removeStr . '" aria-label="' . $removeStr . '"></a>
            </li>
        </ul>
        <input type="hidden" name="o-module-group:group[]">
    </td>
</tr>';
?>
<fieldset id="groups" class="section group" aria-labelledby="groups-label">
    <legend id="groups-legend"><?php echo $translate('Groups'); ?></legend>
    <table id="group-resources" data-tablesaw-mode="stack" class="tablesaw tablesaw-stack <?php echo ($resource && $groups) ? '' : 'empty'; ?>">
        <thead>
        <tr>
            <th><?php echo $translate('Group'); ?></th>
        </tr>
        </thead>
        <tbody>
        <?php
        if ($resource && $groups):
            $resourceName = $resource->getControllerName();
            $group = reset($groups);
            $updateRight = $group->userIsAllowed('update');
        ?>
        <?php foreach ($groups as $group): ?>
        <tr>
            <td>
                <span><?php echo $this->hyperlink($group->name(), $group->adminUrl()); ?></span>
                <ul class="actions">
                    <li>
                        <a href="<?php echo $escape($group->urlEntities('user')); ?>"
                            class="o-icon-user"
                            aria-label="<?php echo $escape($translate('Users within this group')); ?>"
                            title="<?php echo $escape($translate('Users within this group')); ?>"></a>
                        <a href="<?php echo $escape($group->urlEntities('item-set')); ?>"
                            class="o-icon-item-sets"
                            aria-label="<?php echo $escape($translate('Item sets within this group')); ?>"
                            title="<?php echo $escape($translate('Item sets within this group')); ?>"></a>
                        <a href="<?php echo $escape($group->urlEntities('item')); ?>"
                            class="o-icon-items"
                            aria-label="<?php echo $escape($translate('Items within this group')); ?>"
                            title="<?php echo $escape($translate('Items within this group')); ?>"></a>
                        <a href="<?php echo $escape($group->urlEntities('media')); ?>"
                            class="o-icon-media"
                            aria-label="<?php echo $escape($translate('Media within this group')); ?>"
                            title="<?php echo $escape($translate('Media within this group')); ?>"></a>
                        <a href="#" class="o-icon-delete" title="<?php echo $removeStr; ?>" aria-label="<?php echo $removeStr; ?>"></a>
                    </li>
                </ul>
                <input type="hidden" name="o-module-group:group[]" value="<?php echo $escape($group->name()) ?>">
            </td>
        </tr>
        <?php endforeach; ?>
        <?php endif; ?>
        </tbody>
    </table>
    <div class="no-resources">
        <p>
            <?php echo $translate('There are no groups for this resource.'); ?>
            <br />
            <?php echo $translate('Add existing groups using the interface to the right.'); ?>
        </p>
    </div>
    <button id="group-selector-button" class="mobile-only"><?php echo $translate('Add a group'); ?></button>
    <span id="group-template" data-template="<?php echo $escape($groupTemplate); ?>"></span>
    <?php echo $this->groupSelector(); ?>
</fieldset>
