<?php
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
$resourceName = $resource && $resource->getControllerName();
$updateRight = false; // $this->userIsAllowed(GroupUser::class, 'update');
?>
<style>
.group .actions {
    float: right;
}
</style>
<div class="meta-group group">
    <h4><?php echo $translate('Groups'); ?></h4>
<?php if (empty($groups)): ?>
    <div class="value no-value">
        <?php echo $escape($translate('No group.')); ?>
    </div>
<?php else: ?>
    <?php foreach ($groups as $group): ?>
    <div class="value group"><?php echo $this->hyperlink($group->name(), $group->adminUrl()); ?>
    <?php if ($updateRight): ?>
    <span class="single actions"><a href="#"
        class="o-icon-delete"
        data-delete-confirm-url="<?php echo $escape($group->url('delete-confirm')); ?>"
        aria-label="<?php echo $escape($translate('Unassign group')); ?>"
        title="<?php echo $escape($translate('Unassign group')); ?>"></a></span>
    <?php endif; ?>
    <span class="single actions"><a href="<?php echo $escape($group->urlEntities('media')); ?>"
        class="o-icon-media"
        aria-label="<?php echo $escape($translate('Media within this group')); ?>"
        title="<?php echo $escape($translate('Media within this group')); ?>"></a></span>
    <span class="single actions"><a href="<?php echo $escape($group->urlEntities('item')); ?>"
        class="o-icon-items"
        aria-label="<?php echo $escape($translate('Items within this group')); ?>"
        title="<?php echo $escape($translate('Items within this group')); ?>"></a></span>
    <span class="single actions"><a href="<?php echo $escape($group->urlEntities('item-set')); ?>"
        class="o-icon-item-sets"
        aria-label="<?php echo $escape($translate('Item sets within this group')); ?>"
        title="<?php echo $escape($translate('Item sets within this group')); ?>"></a></span>
    <span class="single actions"><a href="<?php echo $escape($group->urlEntities('user')); ?>"
        class="o-icon-user"
        aria-label="<?php echo $escape($translate('Users within this group')); ?>"
        title="<?php echo $escape($translate('Users within this group')); ?>"></a></span>
    </div>
    <?php endforeach; ?>
<?php endif; ?>
</div>
