<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var bool $isUser
 * @var \Group\Api\Representation\GroupRepresentation[] $groups
 * @var \Omeka\Api\Representation\AbstractEntityRepresentation|null $resource
 */

$translate = $this->plugin('translate');
$this->headLink()->appendStylesheet($this->assetUrl('css/group.css', 'Group'));
$this->headScript()->appendFile($this->assetUrl('js/group.js', 'Group'), 'text/javascript', ['defer' => 'defer']);
?>

<style>
.group .group-list {
    list-style-type: none;
    padding-left: 0;
}
.group .actions {
    float: right;
}
</style>
<div class="property group">
<?php if ($isUser): ?>
    <h4><?= $translate('Groups') ?></h4>
    <?php if (empty($groups)): ?>
    <div class="value no-value"><?= $translate('There are no groups for this user.') ?></div>
    <?php endif; ?>
<?php endif; ?>
    <div class="value">
<?php if (empty($groups)): ?>
    <?php if (!$isUser): ?>
    <div class="no-resources">
        <p><?= $translate('There are no groups for this resource.') ?></p>
    </div>
    <?php endif; ?>
<?php else: ?>
        <?php
        $escape = $this->plugin('escapeHtml');
        $updateRight = false; // $this->userIsAllowed(Group::class, 'update');
        $browseUserRight = $this->userIsAllowed('Omeka\Controller\Admin\User', 'browse');
        ?>
        <ul class="group-list">
        <?php foreach ($groups as $group): ?>
            <li class="value group"><?= $this->hyperlink($group->name(), $group->adminUrl()) ?>
                <?php if ($updateRight): ?>
                <span class="single actions"><a href="#"
                    class="o-icon-delete"
                    data-delete-confirm-url="<?= $escape($group->url('delete-confirm')) ?>"
                    aria-label="<?= $escape($translate('Unassign group')) ?>"
                    title="<?= $escape($translate('Unassign group')) ?>"></a></span>
                <?php endif; ?>
                <span class="single actions"><a href="<?= $escape($group->urlEntities('media')) ?>"
                    class="o-icon-media"
                    aria-label="<?= $escape($translate('Media within this group')) ?>"
                    title="<?= $escape($translate('Media within this group')) ?>"></a></span>
                <span class="single actions"><a href="<?= $escape($group->urlEntities('item')) ?>"
                    class="o-icon-items"
                    aria-label="<?= $escape($translate('Items within this group')) ?>"
                    title="<?= $escape($translate('Items within this group')); ?>"></a></span>
                <span class="single actions"><a href="<?= $escape($group->urlEntities('item-set')) ?>"
                    class="o-icon-item-sets"
                    aria-label="<?= $escape($translate('Item sets within this group')) ?>"
                    title="<?= $escape($translate('Item sets within this group')) ?>"></a></span>
                <?php if ($browseUserRight): ?>
                <span class="single actions"><a href="<?= $escape($group->urlEntities('user')) ?>"
                    class="o-icon-user"
                    aria-label="<?= $escape($translate('Users within this group')) ?>"
                    title="<?= $escape($translate('Users within this group')) ?>"></a></span>
                <?php endif; ?>
            </li>
        <?php endforeach; ?>
        </ul>
<?php endif; ?>
    </div>
</div>
