<?php
$translate = $this->plugin('translate');
$this->headLink()->appendStylesheet($this->assetUrl('css/group.css', 'Group'));
$this->headScript()->appendFile($this->assetUrl('js/group.js', 'Group'));
?>
<style>
.group .group-list {
    list-style-type: none;
    padding-left: 0;
}
.group .actions {
    float: right;
}
</style>
<div class="property group">
<?php if ($isUser): ?>
    <h4><?php echo $translate('Groups'); ?></h4>
    <?php if (empty($groups)): ?>
    <div class="value no-value"><?php echo $translate('There are no groups for this user.'); ?></div>
    <?php endif; ?>
<?php endif; ?>
    <div class="value">
<?php if (empty($groups)): ?>
    <?php if (!$isUser): ?>
    <div class="no-resources">
        <p><?php echo $translate('There are no groups for this resource.'); ?></p>
    </div>
    <?php endif; ?>
<?php else: ?>
        <?php
        $escape = $this->plugin('escapeHtml');
        $resourceName = $resource && $resource->getControllerName();
        $updateRight = false; // $this->userIsAllowed(Group::class, 'update');
        ?>
        <ul class="group-list">
        <?php foreach ($groups as $group): ?>
            <li class="value group"><?php echo $this->hyperlink($group->name(), $group->adminUrl()); ?>
                <?php if ($updateRight): ?>
                <span class="single actions"><a href="#"
                    class="o-icon-delete"
                    data-delete-confirm-url="<?php echo $escape($group->url('delete-confirm')); ?>"
                    aria-label="<?php echo $escape($translate('Unassign group')); ?>"
                    title="<?php echo $escape($translate('Unassign group')); ?>"></a></span>
                <?php endif; ?>
                <span class="single actions"><a href="<?php echo $escape($group->urlEntities('media')); ?>"
                    class="o-icon-media"
                    aria-label="<?php echo $escape($translate('Media within this group')); ?>"
                    title="<?php echo $escape($translate('Media within this group')); ?>"></a></span>
                <span class="single actions"><a href="<?php echo $escape($group->urlEntities('item')); ?>"
                    class="o-icon-items"
                    aria-label="<?php echo $escape($translate('Items within this group')); ?>"
                    title="<?php echo $escape($translate('Items within this group')); ?>"></a></span>
                <span class="single actions"><a href="<?php echo $escape($group->urlEntities('item-set')); ?>"
                    class="o-icon-item-sets"
                    aria-label="<?php echo $escape($translate('Item sets within this group')); ?>"
                    title="<?php echo $escape($translate('Item sets within this group')); ?>"></a></span>
                <span class="single actions"><a href="<?php echo $escape($group->urlEntities('user')); ?>"
                    class="o-icon-user"
                    aria-label="<?php echo $escape($translate('Users within this group')); ?>"
                    title="<?php echo $escape($translate('Users within this group')); ?>"></a></span>
            </li>
        <?php endforeach; ?>
        </ul>
<?php endif; ?>
    </div>
</div>
