<?php
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');

// Groups are already sorted.
$groupsByInitial = [];
if (extension_loaded('mbstring')) {
    foreach ($groups as $group) {
        $initial = mb_substr($group->name(), 0, 1);
        $groupsByInitial[mb_strtolower($initial)][] = $group;
    }
} else {
    foreach ($groups as $group) {
        $initial = substr($group->name(), 0, 1);
        $groupsByInitial[strtolower($initial)][] = $group;
    }
}
?>
<div id="group-selector" class='selector sidebar active'>
    <a href="#" class="mobile-only sidebar-close o-icon-close"><span class="screen-reader-text"><?php echo $translate('Close Me'); ?></span></a>
    <h3><?php echo $translate('Click on a group to add it to the edit panel.'); ?></h3>
    <input type="text" class="selector-filter" placeholder="<?php echo $escape($translate('Filter groups')); ?>">
    <ul>
        <li class="total-count-heading"><?php echo $translate('All groups'); ?> (<span class="selector-total-count"><?php echo count($groups); ?></span>)
            <ul class="selectable-list">
                <?php foreach ($groupsByInitial as $initial => $groups): ?>
                    <li class="selector-parent">
                        <span><?php echo $initial; ?></span>
                        (<span class="selector-child-count"><?php echo count($groupsByInitial[$initial]); ?></span>)
                        <ul>
                        <?php foreach($groups as $group): ?>
                            <li class="selector-child" data-child-search="<?php echo $escape($group->name()); ?>" data-group-internal-id="<?php echo $escape($group->id()); ?>">
                                <span><?php echo $escape($group->name()); ?></span>
                            </li>
                        <?php endforeach; ?>
                        </ul>
                <?php endforeach; ?>
            </ul>
        </li>
    </ul>
</div>
