<?php
$translate = $this->plugin('translate');
?>
<div id="group-module" class="mapping-group">
    <a href="#" class="expand" aria-label="<?= $translate('Expand') ?>">
        <h4><?= $translate('Group') ?></h4>
    </a>
    <div class="collapsible">
        <select name="group" class="flags" data-flag-class="group" data-flag-unique="1" data-flag-label="<?= $translate('Groups') ?>">
            <option><?= $translate('Select below') ?></option>
            <option value="1" data-flag-name="column-group"><?= $translate('Group') ?></option>
        </select>
    </div>
</div>
