<div id='group-module' class='sidebar flags'>
    <a href='#' class='sidebar-close o-icon-close'><span class='screen-reader-text'><?php echo $this->translate('Close Me'); ?></span></a>
    <h3><?php echo $this->translate('Group'); ?></h3>
    <ul>
        <li data-flag='column-group' data-flag-type='group-module'>
            <a href='#' class='button'><span><?php echo $this->translate('Group'); ?></span></a>
        </li>
    </ul>

    <div class='group-mapping options'>
        <h4><?php echo $this->translate('Options'); ?></h4>
        <a href='#' class='button column-multivalue'><span><?php echo $this->translate('Use multivalue separator'); ?></span></a>
    </div>
</div>
