<?php
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
$this->htmlElement('body')->appendAttribute('class', 'groups add');
// $this->headScript()->appendFile($this->assetUrl('js/advanced-search.js', 'Omeka'), 'text/javascript', ['defer' => 'defer']);
$form->prepare();
?>
<?= $this->pageTitle($translate('New group'), 1, $translate('Group')) ?>
<?= $this->form()->openTag($form) ?>

<div id="page-actions">
    <button type="submit"><?= $translate('Add') ?></button>
</div>

<?= $this->formCollection($form, false) ?>
<?= $this->form()->closeTag() ?>
