<?php
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
$this->htmlElement('body')->appendAttribute('class', 'groups add');
// $this->headScript()->appendFile($this->assetUrl('js/advanced-search.js', 'Omeka'));
$form->prepare();
?>
<?php echo $this->pageTitle($translate('New group'), 1, $translate('Group')); ?>
<?php echo $this->form()->openTag($form); ?>

<div id="page-actions">
    <button><?php echo $translate('Add'); ?></button>
</div>

<?php echo $this->formCollection($form,false); ?>
<?php echo $this->form()->closeTag(); ?>
