<?php $escape = $this->plugin('escapeHtml'); ?>
<?php $group = $resource; ?>
<div class="resource-details" data-resource-values="<?php // echo $escape($values); ?>">
    <h3 class="o-module-group"><?php echo $group->link($group->name()); ?> <span class="internal-id"><?php echo sprintf('(id: %d)', $group->id()); ?></span></h3>
    <div class="meta-group">
        <h4><?php echo $escape($this->translate('Group')); ?></h4>
        <div class="value">
            <?php if ($comment = $group->comment()): ?>
            <span class="group-comment"><?php echo $escape($comment); ?></span>
            <?php else: ?>
            <span class="group-comment no-comment"><?php echo $escape($this->translate('No comment.')); ?></span>
            <?php endif; ?>
        </div>
    </div>
    <div class="meta-group">
        <h4><?php echo $escape($this->translate('Stats')); ?></h4>
        <div class="value"><?php echo sprintf('%s: %s',
            $escape($this->translate('Total')),
            $groupCount['count']);
        ?></div>
        <div class="value"><?php echo sprintf('%s: %s',
            $escape($this->translate('Users')),
            $this->hyperlink($groupCount['users'], $group->urlEntities('users')));
        ?></div>
        <div class="value"><?php echo sprintf('%s: %s',
            $escape($this->translate('Resources')),
            $groupCount['resources']);
        ?></div>
        <div class="value"><?php echo sprintf('%s: %s',
            $escape($this->translate('Item sets')),
            $this->hyperlink($groupCount['item_sets'], $group->urlEntities('item-set')));
        ?></div>
        <div class="value"><?php echo sprintf('%s: %s',
            $escape($this->translate('Items')),
            $this->hyperlink($groupCount['items'], $group->urlEntities('item')));
        ?></div>
        <div class="value"><?php echo sprintf('%s: %s',
            $escape($this->translate('Medias')),
            $this->hyperlink($groupCount['media'], $group->urlEntities('media')));
        ?></div>
    </div>
</div>
